- include/merlin_hashtable.cuh
This is the isolated change where I cleanup all the thrust invocations.
The type you were looking for is named: uintptr_t
https://en.cppreference.com/w/cpp/types/integer
> [Refactor]Cleanup the thrust invocations.

- README.md
- benchmark/merlin_hashtable_benchmark.cc.cu
- include/merlin/core_kernels.cuh
- include/merlin/types.cuh
- [Opt] optimize the erase performance 
- [Benchmark] add the benchmark for erase
> [Opt] optimize the erase performance 

- benchmark/merlin_hashtable_benchmark.cc.cu
- include/merlin/core_kernels.cuh
- include/merlin/flexible_buffer.cuh
- include/merlin/initializers.cuh
- include/merlin_hashtable.cuh
- include/merlin_localfile.h
Hi, thanks for open source this project，it's a great job！🥂 🍻 
I can reproduce the benchmark.
It may be better to use const keyword before function parameters not modifiable.
> Use const keyword to specify parameter not modifiable

- include/merlin/types.cuh
- include/merlin/utils.cuh
- include/merlin_hashtable.cuh
See code mostly. Let's step through it together.
> [fix] Several minor fixes

- include/merlin_hashtable.cuh
There is a race condition in the export functions. You must lock the table before reading `table_->capacity`.
> Must lock before reading `table_->capacity`.

- include/merlin/core_kernels.cuh
- tests/merlin_hashtable_test.cc.cu
> [Fix] Possible insert fail after erase when table is full.

- include/merlin/core_kernels.cuh
- include/merlin/types.cuh
- include/merlin/utils.cuh
- include/merlin_hashtable.cuh
- tests/merlin_hashtable_test.cc.cu
- [Opt] Switch lock to the atomic lock
- [Opt] Optimize the lookup_kernel_with_io
> [Opt] Optimize the lookup_kernel_with_io

- benchmark/merlin_hashtable_benchmark.cc.cu
- include/merlin/core_kernels.cuh
- include/merlin/types.cuh
- include/merlin_hashtable.cuh
- tests/merlin_hashtable_test.cc.cu
- Optimizing the benchmark
- More rigorous testing
- Using the Atomic key for supporting lock free
- Set up the different block_size for computing kernel and IO kernel
- Add a copy of table configuration struct on device memory
> [Opt] Optimizing the insert API

- include/merlin/core_kernels.cuh
- include/merlin_hashtable.cuh
- tests/merlin_hashtable_test.cc.cu
Co-authored-by: kunlunl <kunlunl@nvidia.com>
> [Opt] select upsert kernel dynamically

- benchmark/merlin_hashtable_benchmark.cc.cu
- include/merlin/core_kernels.cuh
- include/merlin/types.cuh
- include/merlin_hashtable.cuh
- include/merlin_localfile.hpp
- tests/merlin_hashtable_test.cc.cu
- tests/save_and_load_test.cc.cu
- tests/test_util.cuh
- To avoid performance declines, support the TableCore structs in constant memory.
- Optimize some unit cases.
> [Feat] Make dim configurable in runtime.

- CMakeLists.txt
- include/merlin/debug.hpp
- include/merlin/memory_pool.cuh
- include/merlin_hashtable.cuh
- tests/memory_pool_test.cc.cu
See also https://github.com/NVIDIA-Merlin/HierarchicalKV/pull/26 for past discussions.
> [Opt] Resource pooling

- .github/workflows/docs-sched-rebuild.yaml
Refer to https://github.com/NVIDIA-Merlin/NVTabular/pull/1765.
> docs: Rebuild docs on push

- benchmark/merlin_hashtable_benchmark.cc.cu
- include/merlin_hashtable.cuh
- tests/dynamic_max_capacity_test.cc.cu
The first commit is a change that follows the command in the style guide. The second commit is to ensure that both the reserve and fast_load_factor functions can use the stream set in the function that called them
> Use the corresponding stream

- CMakeLists.txt
- README.md
- benchmark/merlin_hashtable_benchmark.cc.cu
- include/merlin/array_kernels.cuh
- include/merlin/core_kernels.cuh
- include/merlin/group_lock.hpp
- include/merlin/types.cuh
- include/merlin_hashtable.cuh
- include/merlin_localfile.hpp
- tests/find_or_insert_test.cc.cu
- tests/group_lock_test.cc
- tests/insert_and_evict_test.cc.cu
- tests/memory_pool_test.cc.cu
- tests/merlin_hashtable_test.cc.cu
- tests/save_and_load_test.cc.cu
- Change insert/assign/evict like API to use unique lock, and find use shared_lock
- Optimize the tests package name
- Fix: https://github.com/NVIDIA-Merlin/HierarchicalKV/issues/118
> [Refactor] lock free with Locked key

- include/merlin/flexible_buffer.cuh
by the way, There is no place to call this class. What is the purpose of the design??
> [Fix] Fixed FlexPinnedBuffer destructor

- include/merlin/core_kernels/upsert_and_evict.cuh
- include/merlin_hashtable.cuh
- tests/insert_and_evict_test.cc.cu
- Add strategy check in `insert_and_evict`
> [Fix] bad data consistency on Customized Strategy

- include/merlin/core_kernels.cuh
- tests/merlin_hashtable_test.cc.cu
[Fix] the offset of keys when init bucket; Unit test about bucket size.
> [Fix] the offset of keys when init bucket; unit test about bucket size.

- include/merlin/core_kernels.cuh
- include/merlin/core_kernels/find_or_insert.cuh
- include/merlin/core_kernels/find_ptr_or_insert.cuh
- include/merlin/core_kernels/lookup.cuh
- include/merlin/core_kernels/lookup_ptr.cuh
- include/merlin/core_kernels/update.cuh
- include/merlin/core_kernels/upsert.cuh
- include/merlin/core_kernels/upsert_and_evict.cuh
- include/merlin/utils.cuh
- include/merlin_hashtable.cuh
- BTW, remove the logic of the constant memory Table
> [Feat] remove all of the `cudaMallocManaged` call

- tests/memory_pool_test.cc.cu
Tries to fix: https://github.com/NVIDIA-Merlin/HierarchicalKV/issues/143
> [bug] Attempt to fix GPU/CPU race condition of the memory pool test.

- include/merlin/core_kernels/group_lock_kernels.cuh
- include/merlin/group_lock.cuh
- include/merlin_hashtable.cuh
- tests/group_lock_test.cc.cu
- [Fix&Opt] Make group lock mount to cuda stream.
> [Feat&Opt] triple-group lock 

- include/merlin/core_kernels.cuh
- include/merlin/core_kernels/kernel_utils.cuh
- include/merlin/group_lock.cuh
- include/merlin/memory_pool.cuh
> support c++11/c++14 compile

- include/merlin/core_kernels/lookup.cuh
- include/merlin_hashtable.cuh
Instead, will check the compute capability in Runtime.
Therefore, users(like SOK) who have general purpose requirement don't need to care about the hardware any more.
> [Fix] Remove ArchTag from the template parameters of HKV.

- CMakeLists.txt
- include/merlin/core_kernels.cuh
- include/merlin/core_kernels/update_values.cuh
- include/merlin_hashtable.cuh
- tests/assign_values_test.cc.cu
- Add `check_evict_strategy` for `assign`
> [Feat] add the API `assign_values`

- include/merlin_hashtable.cuh
Add a virtual base class for more flexibility
> Add virtual base class HashTableBase

- README.md
a better wording for reserved_key_start_bit
> update REDAME for reserve key

- .github/workflows/docs-build.yaml
- .github/workflows/docs-sched-rebuild.yaml
- include/merlin/core_kernels/group_lock_kernels.cuh
- include/merlin/types.cuh
Fix existed issue(https://github.com/NVIDIA-Merlin/HierarchicalKV/issues/206) for using latest CI image.
> [Fix] compile errors on new image

- include/merlin_hashtable.cuh
If users can guarantee there is no conflict across API calls, its better to make the API lock optional.
The default behavior is the same as before, and Performance-sensitive users can init the table using `HashTableOptions.api_lock=false;`
> Make API lock optional when init.

- tests/test_util.cuh
Minor bugfix, as discussed on Slack today.
> This is actually a function call, not a field.
